### ISSUE TITLE
Ajouter une marge dans le chat

### ISSUE THREAD

**Issue by TheBdouilleur** [TheBdouilleur2/jesite#14]
Le corps du chat est collé au bord gauche de l'écran. Ajouter une marge le rendrait beaucoup plus pro

**Comment by TheBdouilleur2** [comment]
Dit moi si la marge te va.

**Comment by TheBdouilleur** [comment]
J'ai pas testé mais à première vue je dirais plutot 7% de marge

**Comment by TheBdouilleur2** [comment]
Je fait un nouveau commit avec une meilleure marge dis moi ce que tu en pense.
