### ISSUE TITLE
Probleme affichage projets dans admin

### ISSUE THREAD

**Issue by TheBdouilleur2** [TheBdouilleur2/jesite#20]
Je travail la page admin et j'ai un probleme, pour afficher les projets je doit charger le class projectManager mais je ne peut pas car elle dépend de manager et que j'ai déjà chargé la class usersManager qui en dépend aussi.
Quelqu'un aurrait il une solution?

**Comment by TheBdouilleur** [comment]
Tu peux réexpliquer pour un pauvre JE largué?

**Comment by TheBdouilleur2** [comment]
C'est bon j'ai résolu le problème. En php, tu apelle un fichier avec ```require($monFicher)```.
J'avais appeler deux fichiers qui appeler chacun le même fichier. J'ai juste mis ```require_once()``` qui n'apelle le fichier que si il n'a pas déja été appeler.
