### ISSUE TITLE
Nouvelle page admin

### ISSUE THREAD

**Issue by TheBdouilleur2** [TheBdouilleur2/jesite#23]
Pour la nouvelle page admin, j'ai mis la liste des utilisateurs et celle des projets, as tu d'autres idées?

**Comment by TheBdouilleur** [comment]
Tu pourrais déplacer le chat sur la page admin

**Comment by TheBdouilleur** [comment]
Ca serait stylé si il y avait des onglets, au lieu que Utilisateurs et Projets soient sur la même page

**Comment by TheBdouilleur2** [comment]
Ok. Et un onglet pour le chat?

**Comment by TheBdouilleur** [comment]
Ouais comme ça tout serait centralisé dans l'espace admin

**Comment by TheBdouilleur2** [comment]
Ok je vais mis mettre dès que j'ai finit les commentaires

**Comment by TheBdouilleur2** [comment]
C'est bon, c'est fait.
