### ISSUE TITLE
Ajouter un champ online pour les projets

### ISSUE THREAD

**Issue by TheBdouilleur2** [TheBdouilleur2/jesite#34]
- [x] Creer le champ
- [x] Ajouter les boutons pour le création du projet
- [x] Ajouter les onglets dans la page projets
- [x] Permettre de retirer un projet

**Comment by TheBdouilleur** [comment]
> Ajouter un champ online pour les projets
C'est à dire?

**Comment by TheBdouilleur2** [comment]
Un champ dans la bdd pour dire si le projet est en ligne ou pas

**Comment by TheBdouilleur** [comment]
Ah ok

**Comment by TheBdouilleur2** [comment]
Comment puis-je marquer le fait que le projet n'est pas en ligne?

**Comment by TheBdouilleur2** [comment]
J'ai mis un tag vert 'Publié' pour les projets en lignes.
